#!/usr/bin/env python3
"""
Test script for a specific RFID code
"""

import asyncio
import sys
import json
from pathlib import Path
from datetime import datetime

# Add src to path
sys.path.insert(0, str(Path(__file__).parent / "src"))

from thermal_printer import ThermalPrinter, ThermalPrinterConfig
from moon_phase import MoonPhaseCalculator
from astrology import AstrologyCalculator
from suit_context import SuitContext
from rfid_mapper import RFIDCardMapper


async def test_rfid_card(rfid_code: str):
    """Test output for a specific RFID code."""
    
    # Configure printer for simulation
    config = ThermalPrinterConfig(
        simulation_mode=True,
        output_file=f"rfid_{rfid_code.replace(':', '-')}_output.txt"
    )
    
    # Create printer
    printer = ThermalPrinter(config)
    await printer.initialize()
    
    # Map RFID to card number
    mapper = RFIDCardMapper("data/rfid_mappings.json")
    card_num = mapper.uid_hex_to_card(rfid_code)
    
    if not card_num:
        print(f"❌ RFID code {rfid_code} not found in mappings!")
        return
    
    print(f"\n🔮 Testing RFID Code: {rfid_code}")
    print(f"📍 Maps to Card: {card_num}")
    
    # Load card data
    with open('data/oracle_cards.json', 'r') as f:
        all_cards = json.load(f)
        card_data = all_cards[card_num - 1]
    
    print(f"🃏 Card Title: {card_data['title']}")
    
    # Get celestial context
    moon_calc = MoonPhaseCalculator()
    moon_context = moon_calc.get_current_phase()
    
    astro_calc = AstrologyCalculator()
    astro_context = astro_calc.get_current_zodiac()
    
    # Get suit context
    suit_loader = SuitContext("data/suits.json")
    suit_context = suit_loader.get_suit_by_card(card_num)
    
    print(f"♠️  Suit: {suit_context['name']} (Cards {suit_context['card_range'][0]}-{suit_context['card_range'][1]})")
    print(f"🌙 Moon: {moon_context['name']}")
    print(f"♈ Zodiac: {astro_context['name']} ({astro_context['element']})")
    
    # Create fortune data
    fortune_data = {
        'haiku': 'Placeholder haiku\nWill be generated by LLM\nIn production mode',
        'title': card_data['title'],
        'description': card_data['description'],
        'keywords': card_data.get('keywords', []),
        'theme': card_data.get('theme', 'Oracle guidance')
    }
    
    print(f"\nGenerating thermal printer output to: {config.output_file}\n")
    
    # Print the fortune
    await printer.print_oracle_fortune(
        fortune_data,
        rfid_code=rfid_code,
        moon_context=moon_context,
        astro_context=astro_context,
        suit_context=suit_context
    )
    
    await printer.shutdown()
    
    # Read and display the output
    output_path = Path(config.output_file)
    if output_path.exists():
        print(f"✅ Output file created: {output_path}\n")
        print(f"{'='*60}")
        print(f"THERMAL PRINTER OUTPUT FOR RFID {rfid_code}")
        print(f"{'='*60}\n")
        
        with open(output_path, 'r', encoding='utf-8') as f:
            content = f.read()
            # Skip the timestamp lines and just show the actual content
            lines = content.split('\n')
            for i, line in enumerate(lines):
                if '---' not in line:
                    print(line)
        
        print(f"\n{'='*60}\n")
        
        # Validation checks
        checks = [
            ("Card Title", card_data['title'].upper() in content),
            ("Card Number", f"CARD {card_num}" in content),
            ("Suit Name", suit_context['name'].upper() in content or suit_context['name'] in content),
            ("Suit Essence", suit_context.get('essence', '') in content),
            ("Moon Phase", moon_context['name'] in content),
            ("Zodiac Sign", astro_context['name'] in content),
        ]
        
        print("📋 Content Validation:")
        for field, found in checks:
            status = "✅" if found else "❌"
            print(f"  {status} {field}: {'Present' if found else 'MISSING'}")
    
    else:
        print(f"❌ Output file not created: {output_path}")


if __name__ == "__main__":
    rfid_code = "04:26:72:5A:06:1F:91"
    asyncio.run(test_rfid_card(rfid_code))

